### ISSUE TITLE
Enable use of config.js also for bot token

### ISSUE THREAD

**Issue by PranavDEV21** [Welcome-Bot/welcome-bot#21]
I need config.js for bot tokens in discord as .env causes problem to create the bot and to fork the source code of a particular bot . So I need config.js as to put my bot tokens.

Thank you,
PRANAV
DISCORD VERIFIED BOT DEVELOPER

**Comment by PuneetGopinath** [comment]
Hi @PranavDEV21!
Thanks for opening the feature request!
Looks good, I and abhijoshi2k will work together on this!

Thanks,
Puneet Gopinath

**Comment by PranavDEV21** [comment]
Ok

**Comment by PuneetGopinath** [comment]
Hi!
But abhijoshi2k doesn't like this idea
It is easy to create a .env file
So closing this issue

**Comment by abhijoshi2k** [comment]
@PranavDEV21 In case you can't use/add a .env, another option is to directly hard-code the values by replacing the environment variables wherever used.
Using the global search on vscode would be helpful. The search string would be `process.env.`
Hope this helps. ☺️

**Comment by PuneetGopinath** [comment]
> @PranavDEV21 In case you can't use/add a .env, another option is to directly hard-code the values by replacing the environment variables wherever used.
> Using the global search on vscode would be helpful. The search string would be `process.env.`
> Hope this helps. ☺️

I actually said that
